#+TITLE: Steffe
#+OPTIONS: toc:nil
#+OPTIONS: num:0

- [[file:program.pdf][Program]]

- Tal till Steffe

  Vi möts här idag för att minnas ett litet barn som dött och för att
  hjälpa varandra att acceptera hans död. Han hann inte utveckla en
  personlighet men var en mycket viktig person för dem som längtade
  efter och redan älskade honom. Den vida cirkeln av hans familj och
  deras vänner känner djupt förlusten av honom och deltar i de närmastes
  stora sorg.

  Vi hade alla längtat så mycket. Det skulle bli så fint och roligt att
  få ta hand om och lära känna en ny person i vår stora familj. En dag i
  somras hade en av oss tröttnat på att säga "den" och kallade skämtsamt
  barnet i magen för Steffe. Vi skrattade och namnet fastnade. När han
  kom ut var det inget tvivel om att det var en Steffe som vi hade fått
  och mist så hastigt. Nu minns vi för alltid den fina lilla stora
  pojken som Steffe.

  Låt Steffe stanna i era tankar. Det finns ingen anledning att lämna
  honom för fort. Tala ofta om Steffe, tänk på honom och på alla andra
  som lärt känna honom lite grann genom vår längtan och våra
  förberedelser. Vi glömmer aldrig lille Steffe.

- [[file:Steffe.mp3][Sång till Steffe]], Sophie Zelmani

- Morgon, Karin Boye

  : När morgonens sol genom rutan smyger,
  : glad och försiktig,
  : lik ett barn, som vill överraska
  : tidigt, tidigt en festlig dag --
  : då sträcker jag full av växande jubel
  : öppna famnen mot stundande dag --
  : ty dagen är du,
  : och ljuset är du,
  : solen är du,
  : och våren är du,
  : och hela det vackra, vackra,
  : väntande livet är du!

- [[file:Jag%20ger%20dig%20min%20morgon.mp3][Jag ger dig min morgon]], Fred Åkerström

- Dikt, Harry Martinsson

  : Varje djup sorg har förlorad glädje till föremål.
  : Tappa inte bort denna riktning.
  : Låt inte sorgen glömma sitt ärende.
  : Sorgen är den djupaste ära glädjen kan få.

- Stycken framförda på orgel:
  
  - [[https://www.youtube.com/results?search_query%3Dpriere%2Bnotre-dame%2Bleon%2Bboellmann][Prière à Notre-Dame]], Léon Boëllmann

  - [[https://www.youtube.com/results?search_query%3Demigrantvisa%2Bjan%2Bjohansson][Emigrantvisa]], Jan Johansson 
    
  - [[https://www.youtube.com/results?search_query%3Dberceuse%2Barmas%2Bj%25C3%25A4rnefelt][Berceuse]], Armas Järnefelt
