* condolences
** erinn
Linus, I am so so so incredibly sorry. I'm sending you and Gertrud and the
girls all my love in this devasting time. My deepest condolences. :( RIP sweet
baby.
** roger
!! That is very sad. :(

Rachel and I are thinking of you.

And let us know if we can do anything to help.

--Roger
** jake
(!!!!!)

I'm so sorry Linus. There are no words. :(

If there is anything that needs to be done, please tell us and we'll do it!

You both have all of my love,
-Jake
** andrew
Linus and Gertrude,

Sarah and I are greatly saddened to hear this news. Our deepest
condolences. No matter how deep your grief and pain, no matter how alone
you feel, you are not alone. You have each other, and you have us.

We're available to call, to talk, to listen if ever the need strikes
either of you. +1-781-948-1982.

Please let us know where to send flowers and condolences.
** pawal
Fyfan vad läskigt. Har varit med om något liknande. Mina sympatier till
er båda.
** robban
vi är otroligt sorgsna och vet inte heller vad vi skall
skriva/säga. Vi tänker på er.
** susanne lager 2014-11-24
Hej Linus, 
Tack för att du ringde igår. Jag har pratat med Susanne.

Mitt absolut varmaste deltagande till er båda, de finaste. 
Det är så ofattbart och så oerhört oerhört orättvist. 
Kan jag hjälpa på nåt endaste sätt så gör jag det, säg bara pip så kommer jag! 
Jag hör av mig igen. 

Mina varmaste tankar och kramar, 
er Susanne 
** sarah 2014-11-24
Hi Linus,just wanted to say,how sorry I am to hear your sad
news. Condolences to Gertrude. Our thoughts are with you in this
difficult time.
** ako 2014-11-24
Käraste ni!

Vi har tänt ett ljus för er ikväll. Vi är så ledsna och önskar att vi
kunde göra allt bra. Ta hand om varandra. Tusen kramar från Ako, Vega
och Humla.
** susanne banck
I want you to know, that we are thinking of you and your girlfriend and the
great loss, you have experienced.
If theres anything we can do to support you in the next period, do contact
me.

All the best thoughts

BR


Susanne
** erik 2014-11-25
En nattlig tanke på / till er båda. 
Just nu kämpar ni på. 
Snart får vi lite grand veta mer om vem den lilla krabaten är, som
hållit dig vaken och hållit dig sällskap den senaste tiden,
Gertrud. Och som hållit oss andra, oss alla, nyfikna och glada och
förväntansfulla.
Godnatt! Hoppas ni får sova snart också!
Kram,
Erik
** fredde 2014-11-25
Jag är så ledsen, vi tänker på er hela tiden. Kram från oss
** nisse 2014-11-25
Hej. Erik har berättat om ert barns fruktansvärda olycka. Vi tänker på
dig och Gertrud och hoppas ni snart mår bra igen. /Nisse
** marianne 2014-11-25
Kära Gertrud och Linus!

Jag tänker så mycket på er. Det är helt ofattbart och så otroligt
sorgligt att inte lille Steffe fick ett liv tillsammans med er.
Hoppas att ni blir väl omhändertagna och att du, Gertrud, mår bra
efter din stora bragd.

Varma kramar
Marianne
** tg 2014-11-26
Hej,

Jag såg Gertruds statusuppdatering på FB häromdagen. Stackars er båda
två. Ifall du vill ses eller känner att du behöver prata med någon så
hör gärna av dig. Hälsa Gertrud också.

-TG
** andreas 2014-11-30
Hej,
Jag skriver det här mailet lite utan en plan, för allt jag har att säga
känns så fattigt. Jag har tänkt mycket på dig, Gertrud, Juni och Lärka
sedan du ringde, och samtidigt som att jag inte vill störa er, så vill
jag inte heller ge sken av att jag inte bryr mig för det gör jag.
Samtidigt är jag rädd för att störa.

Vill nog bara säga att jag inte försvunnit och om det finns något som
jag kan göra så behöver jag bara veta vad. Det är självklart ett stående
erbjudande.

Du behöver så klart inte svara, eller föra vidare hälsningar om det inte
känns ok eller om du inte orkar, annars; krama där det passar, jag
tänker på er.

Andreas
** george 2014-12-01
oh my!

that's indeed very sad news, linus.
sorry for this bad luck, and hope you all the best for the future.

i hope you are all well and keep strong! 
** georg 2014-12-03
Hej!

> Hej Georg!
>
> Jag har väldigt tråkiga nyheter. Barnet dog innan födseln. Jag blir borta
> ett tag.

Jag saknas ord. Det är så synd och tråkigt. Vi hoppades att ni skulle ha det
roligt med erat små barn påminnat hur det var med Hanna, Wiebke och Nils när
de var så små... Vi ber att få beklaga sorgen.

> Hälsa din familj. Vi tyckte båda att det var en fin kväll tillsammans
> med alla dina spralliga och roliga barn.

Det tyckte (och fortfarande tycker) vi också. Barnen frågade redan flera
gånger när vi åker till Stockholm igen. Nils bestämde sig faktiskt att vi
gör det fyra gånger nästa året. Vi ska se...

> Vi hörs framöver.

Det gör vi. I alla fall.

Kramar,

Georg och hela familjen
** nick and susan 2014-12-12
Dear Linus,

Susan and I just found out about your loss. (The original email from
Andrew had gotten buried in my email.)  We're so heartbroken for you;
please know that you have our unconditional support in any way you
need.

sincerely yours,
--
Nick Mathewson
Susan Born

** #tor-internal 2014-12-27--28
<saint> ln5: I'm so sorry =(  Please take time for yourself and your family
<sysrqb> ln5: *hugs* that's terrible! please let us know if we can help you or support you
<dgoulet> ln5: ah my... so sorry to hear that :S, take the time you need with your family and off the Internet!
<athena> ln5: *offers belated hugs as catching up on IRC backlog*
<Runa> ln5: :( hugs
<puffin_> ln5: :( my condolences
<weasel> ln5: I'm so very sorry to hear that.  Lots of strength to you two in this hard time.
<isis> ln5: i'm so sorry!
<isis> ln5: is there anything i could do to try to help cheer you up?
<isis> ln5: it would probably be a rather poor consolation, but could we send you a club mate?
mrphs sends hugs++ to ln5

* begravningen
** program

1. Intåg till orgelmusik
   Prière à Notre-Dame av Léon Boëllmann

2. Tal till Steffe, läses av Lo Kauppi

3. Sång till Steffe, av Sophie Zelmani, CD

4. Morgon [1], av Karin Boye, läses av Lo Kauppi

5. Jag ger dig min morgon, av Fred Åkerström, CD

6. Ett sista farväl vid kistan, med orgelmusik 
   [titel, upphovsperson]

7. Dikt av Harry Martinson [2], läses av Lo Kauppi

8. Uttåg till orgelmusik
   Berceuse av Armas Järnefelt


[1] När morgonens sol genom rutan smyger,
    glad och försiktig,
    lik ett barn, som vill överraska
    tidigt, tidigt en festlig dag --
    då sträcker jag full av växande jubel
    öppna famnen mot stundande dag --
    ty dagen är du,
    och ljuset är du,
    solen är du,
    och våren är du,
    och hela det vackra, vackra,
    väntande livet är du!

[2] Varje djup sorg har förlorad glädje
        till föremål.
    Tappa inte bort denna riktning.
    Låt inte sorgen glömma sitt ärende.
    Sorgen är den djupaste ära glädjen
        kan få.
** Tal till Steffe
Vi möts här idag för att minnas ett litet barn som dött och för att
hjälpa varandra att acceptera hans död. Han hann inte utveckla en
personlighet men var en mycket viktig person för dem som längtade
efter och redan älskade honom. Den vida cirkeln av hans familj och
deras vänner känner djupt förlusten av honom och deltar i de närmastes
stora sorg.

Vi hade alla längtat så mycket. Det skulle bli så fint och roligt att
få ta hand om och lära känna en ny person i vår stora familj. En dag i
somras hade en av oss tröttnat på att säga "den" och kallade skämtsamt
barnet i magen för Steffe. Vi skrattade och namnet fastnade. När han
kom ut var det inget tvivel om att det var en Steffe som vi hade fått
och mist så hastigt. Nu minns vi för alltid den fina lilla stora
pojken som Steffe.

Låt Steffe stanna i era tankar. Det finns ingen anledning att lämna
honom för fort. Tala ofta om Steffe, tänk på honom och på alla andra
som lärt känna honom lite grann genom vår längtan och våra
förberedelser. Vi glömmer aldrig lille Steffe.
* folkbokföring
- https://www4.skatteverket.se/rattsligvagledning/edition/2015.10/330294.html
- skickade brev till skatteverket med bristfälliga uppgifter
- skickade brev med fullst. uppgifter till skatteverket 27 mars 2015
- ringde folkbokförningen <2015-08-05 Wed>
  - första personen jag pratade med kunde bara se adressändring den 28
    april 2015
  - blev kopplad till en handläggare, "marianne"
  - född 2014-11-25 hittar hon, AFB-relation med bägge föräldrar registrerat
  - namn steffe nordberg kleberg registrerat
  - AFB-relation blev registrerad 10 april
  - syns inte i personbeviset (för steffe)
  - skickar registerutdrag på steffe och personbild på både linus och
    gertrud med posten
